### ISSUE TITLE
Parameter Types in Output file

### ISSUE THREAD

**Issue by rjhicks41** [alistanis/cf_parameter_generator#1]
currently the output parameter file has parameter statements that look like this:

 {
    "ParameterKey": "ELBSecurityGroups",
    "ParameterValue": ""
  },

Would be fantastic to add some descriptive text to the ParameterValue line explaining the parameter type.  For example:

 {
    "ParameterKey": "ELBSecurityGroups",
    "ParameterValue": "Type: List<AWS::EC2::SecurityGroup::Id>"
  },

**Comment by alistanis** [comment]
This support was merged in in commit https://github.com/alistanis/cf_parameter_generator/commit/22289ef075e2510ebd29d6757a3226677a86eccd

Thanks for the suggestion!
