### ISSUE TITLE
Could use some more / improved usage examples

### ISSUE THREAD

**Issue by rjhicks41** [alistanis/cf_parameter_generator#2]
the README could use some more examples of the usage of the application to demonstrate interactions between the various flags that are available.

**Comment by alistanis** [comment]
Merged in in https://github.com/alistanis/cf_parameter_generator/commit/22289ef075e2510ebd29d6757a3226677a86eccd and https://github.com/alistanis/cf_parameter_generator/commit/3525b9bce8d92db58bafeb72e3e39f78aff3afa2

Again, thanks for the suggestion!
